### ISSUE TITLE
Investigations

### ISSUE THREAD

**Issue by GeertvanHorrik** [TradeItEasy/Compiled-Bindings#1]

**Comment by GeertvanHorrik** [comment]
Will keep pushing info here.

**Comment by TradeItEasy** [comment]
Ok, great.

**Comment by TradeItEasy** [comment]
Yes it's definitely a problem in the VM implementation. In the generated code it tries to call RegisterPropertyChangedCallback and UnregisterPropertyChangedCallback on the ViewModel.

**Comment by GeertvanHorrik** [comment]
I am trying to figure out the logic it uses to determine what methods to call. It's weird that it doesn't just check for base classes.

**Comment by GeertvanHorrik** [comment]
Found implementation in Microsoft.VisualStudio.DesignTools.XamlLanguageService

**Comment by TradeItEasy** [comment]
Mhhh, did you find the source of the XAML compiler? Could you provide me with a link? I though it would be part of MSBuild...

**Comment by GeertvanHorrik** [comment]
Not sure yet, found the tool implementation, but that passes stuff to Roslyn, so might need to dig a bit deeper.

**Comment by GeertvanHorrik** [comment]
So just to be clear, the issue is that it's generating (treating) a VM like it's a dependency object:

```
public void DependencyPropertyChanged_VM_Visible(global::Windows.UI.Xaml.DependencyObject sender, global::Windows.UI.Xaml.DependencyProperty prop)
{
    MainView_obj1_Bindings bindings = TryGetBindingObject();
    if (bindings != null)
    {
        global::CatelCompiledBinding.ViewModels.MainViewModel obj = sender as global::CatelCompiledBinding.ViewModels.MainViewModel;
        if (obj != null)
        {
            bindings.Update_VM_Visible(obj.Visible, DATA_CHANGED);
        }
    }
}
private global::CatelCompiledBinding.ViewModels.MainViewModel cache_VM = null;
private long tokenDPC_VM_Visible = 0;
public void UpdateChildListeners_VM(global::CatelCompiledBinding.ViewModels.MainViewModel obj)
{
    if (obj != cache_VM)
    {
        if (cache_VM != null)
        {
            ((global::System.ComponentModel.INotifyPropertyChanged)cache_VM).PropertyChanged -= PropertyChanged_VM;
            cache_VM.UnregisterPropertyChangedCallback(global::CatelCompiledBinding.ViewModels.MainViewModel.VisibleProperty, tokenDPC_VM_Visible);
            cache_VM = null;
        }
        if (obj != null)
        {
            cache_VM = obj;
            ((global::System.ComponentModel.INotifyPropertyChanged)obj).PropertyChanged += PropertyChanged_VM;
            tokenDPC_VM_Visible = obj.RegisterPropertyChangedCallback(global::CatelCompiledBinding.ViewModels.MainViewModel.VisibleProperty, DependencyPropertyChanged_VM_Visible);
        }
    }
}
```

![image](https://user-images.githubusercontent.com/1246444/45155944-df2d2780-b1dc-11e8-8ada-97cee089e040.png)

**Comment by TradeItEasy** [comment]
Yes, that is the way I understand the generated code...

**Comment by TradeItEasy** [comment]
I have extracted the diagnostic build log. Lines 28134 onwards are interesting to understand what's happening and where - I guess. This log lead me to investigate the MSBuild pipeline. There is a task called BuildXAML which lead me to investigate this repo https://github.com/Microsoft/msbuild/tree/master/src/Tasks but I did not fully understand how things are going from there...

[BuildLog.txt](https://github.com/TradeItEasy/Compiled-Bindings/files/2356943/BuildLog.txt)

**Comment by GeertvanHorrik** [comment]
The real code generation (with the wrong file) seems to start on line 148892:

```
2>  Task Parameter:ForceSharedStateShutdown=False (TaskId:554)
2>  Task Parameter:CompileMode=RealBuildPass1 (TaskId:554)
2>  Task Parameter:XAMLFingerprint=True (TaskId:554)
2>  Task Parameter:FingerprintIgnorePaths=C:\Program Files (x86)\Windows Kits\10\ (TaskId:554)
2>  Task Parameter:VCInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\ (TaskId:554)
2>  Task Parameter:SavedStateFile=obj\x64\Debug\\XamlSaveStateFile.xml (TaskId:554)
2>  Task Parameter:TargetPlatformMinVersion=10.0.16299.0 (TaskId:554)
2>  Task Parameter:WindowsSdkPath=C:\Program Files (x86)\Windows Kits\10\ (TaskId:554)
```

Which results in the output files:

```
2>  Output Item(s): 
2>      Compile=
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\App.g.i.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\App.g.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\Views\MainView.g.i.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\Views\MainView.g.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\XamlTypeInfo.g.cs (TaskId:554)
2>  Output Item(s): 
2>      FileWrites=
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\App.g.i.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\App.g.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\Views\MainView.g.i.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\Views\MainView.g.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\XamlTypeInfo.g.cs (TaskId:554)
2>  Output Item(s): 
2>      FileWrites=
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\App.xaml
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\Views\MainView.xaml (TaskId:554)
2>  Output Item(s): 
2>      FileWrites=
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\App.xbf
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\Views\MainView.xbf (TaskId:554)
2>  Output Item(s): 
2>      _GeneratedCodeFiles=
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\App.g.i.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\App.g.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\Views\MainView.g.i.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\Views\MainView.g.cs
2>          D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\obj\x64\Debug\XamlTypeInfo.g.cs (TaskId:554)
```

**Comment by TradeItEasy** [comment]
Yes you are right - he somehow does two compile passes. The build task remains the same one though 146598:

```
2>Using "CompileXaml" task from assembly "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Build.Tasks.dll".
2>Task "CompileXaml" (TaskId:554)
2>  Task Parameter:LanguageSourceExtension=.cs (TaskId:554)
2>  Task Parameter:Language=C# (TaskId:554)
2>  Task Parameter:RootNamespace=CatelCompiledBindingTest (TaskId:554)
2>  Task Parameter:
2>      XamlPages=
2>          Views\MainView.xaml
2>                  Generator=MSBuild:Compile
2>                  SubType=Designer (TaskId:554)
2>  Task Parameter:
2>      XamlApplications=
2>          App.xaml
2>                  Generator=MSBuild:Compile
2>                  SubType=Designer (TaskId:554)
2>  Task Parameter:ProjectName=CatelCompiledBinding (TaskId:554)
2>  Task Parameter:IsPass1=True (TaskId:554)
2>  Task Parameter:ProjectPath=D:\Magnus Meseck\Desktop\Catel\Compiled Bindings\CatelCompiledBinding\CatelCompiledBinding.csproj (TaskId:554)
2>  Task Parameter:OutputPath=obj\x64\Debug\ (TaskId:554)
2>  Task Parameter:OutputType=AppContainerExe (TaskId:554)
2>  Task Parameter:
2>      ReferenceAssemblies=...
```

**Comment by TradeItEasy** [comment]
So the question is where to find the code for Microsoft.Windows.UI.Xaml.Build.Tasks.dll. And I think it's closed source as far as my research goes. So where would you raise an issue? In the MSBuild repo? Straight down to Microsoft (as it's their SDK)?

**Comment by GeertvanHorrik** [comment]
It's easy, it's here:

C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Build.Tasks.dll

Then search for CSharpPagePass2 (that's where the magic seems to happen).

**Comment by GeertvanHorrik** [comment]
I've contacted both @davkean & @clintrutkas via twitter. Let's see where that takes us, hopefully to the right people to report this (for now seemingly) bug in the Xaml compiler.

**Comment by GeertvanHorrik** [comment]
Check out `private void Output_UpdateChildListeners`, that's the part generating the corrupt code. Looks like it thinks there are `DependencyPropertyStep` elements. Going to look into the object that gathers this info now.

**Comment by TradeItEasy** [comment]
Ok, Geert, I am too new to development to follow what you are doing. How do you open the manifest of the .dll. Do you use Ildasm?

**Comment by GeertvanHorrik** [comment]
Found the code:

Type: `Microsoft.Xaml.XamlCompiler.BindingPathListener`
Method: `ResolveName(string, XamlType, BindingPathStep)`

Here is the (seemingly) broken code:

```
    case MemberTypes.Property:
        {
            PropertyInfo info = memberInfos[0] as PropertyInfo;
            bool flag = type.UnderlyingType.GetMember(name + "Property", BindingFlags.GetProperty | BindingFlags.GetField | BindingFlags.FlattenHierarchy | BindingFlags.Public | BindingFlags.Static).Length > 0;
            XamlType xamlType = type.SchemaContext.GetXamlType(info.PropertyType);
            if (flag)
            {
                return new DependencyPropertyStep(name, xamlType, parentStep, this.BindingItem.Parent.ApiInformation);
            }

            [CODE LEFT OUT FOR READABILITY]
            
        }
```

btw. using .NET Reflector, but you can use dotPeek as well:

https://www.jetbrains.com/decompiler/

**Comment by GeertvanHorrik** [comment]
As you can see, it *just* checks whether a member called `[MyProperty]Property` exists. If so, it *just assumes* it's a dependency property...

This could be fixed by checking whether any of the base classes (up to the root) implements `DependencyObject`.

This bug simply means that if you have a model with this code:

```
public class MyModel : INotifyPropertyChanged
{
    public string FirstName { get; set; }

    public string FirstNameProperty { get; set; }
}
```

would be compiled as if it was a dependency object.

**Comment by GeertvanHorrik** [comment]
Bug confirmed, just add this to the example:

```
        public bool Visible { get; set; }
        public static string VisibleProperty;
```

And stuff will break.

**Comment by TradeItEasy** [comment]
Wow, very interesting debugging journey here. Now I understand why not having the source is not too much of an issue - dotPeek is a pretty cool tool!
Thanks a lot for looking into this and letting me know the steps you took. Definitely learned a lot today!

Do you think things are settled by having contacted @davkean & @crutkas? Can I close this issue?

**Comment by GeertvanHorrik** [comment]
Please keep it open so they can look at it. They will probably ask for a repro (which we can now easily provide) + an official bug report, just need to find out where.

**Comment by crutkas** [comment]
Can you guys create a small repro I can pass to the xaml team?

**Comment by TradeItEasy** [comment]
This repository is already pretty minimal and may help understand the context in which the problem occurs but I have created another even more stripped down repro here: https://github.com/TradeItEasy/XAMLCompilerPropertyScanningDemo

**Comment by GeertvanHorrik** [comment]
Thanks @TradeItEasy , that is the most minimal example one could create :)

@crutkas thanks for responding, much appreciated.

**Comment by GeertvanHorrik** [comment]
@crutkas is there some public place where we can follow the progress on this issue?

**Comment by crutkas** [comment]
still asking a team to look into this.

**Comment by danzil** [comment]
Hi guys, this is a bug in the Xaml Compiler where, if a type has an instance property Foo and another static property FooProperty, it incorrectly assumes that FooProperty is a DependencyProperty and generates code to listen to its notifications because the binding in question is OneWay. It should also look at FooProperty's type, but it does not and hence the wrong code is generated. I have opened a bug to track this issue. Thanks for reporting it and sorry about the inconvenience!

**Comment by GeertvanHorrik** [comment]
@danzil Thanks for looking into it, glad it's confirmed and will be fixed!
